// ─────────────────────────────────────────────────────────────────────────
// REAL agent data. Generated by  agent/build_reviewer_data.py  from the golden
// set + the 7-gate pipeline. DO NOT hand-edit reviewer_data.json — re-run the
// builder (add a golden case → it runs live once, caches, and this file updates).
// ─────────────────────────────────────────────────────────────────────────
import data from "@/data/reviewer_data.json";

export type Queue = "MIS" | "PV";
export type Severity = "CRITICAL" | "HIGH" | "STANDARD";
export type Status = "READY TO APPROVE" | "NEEDS REVIEW" | "AWAITING INFO";

export interface Field {
  label: string;
  value: string;
  dot: "g" | "a"; // green = looks good · amber = needs attention (empty / failed a check)
  note: string; // why it needs attention (shown only when amber)
  evidence: string; // verbatim source span that grounds this value ('' = not located)
  reason: string; // LLM's one-line why, for interpreted fields ('' = none)
  kind: "text" | "enum" | "list";
  options: string[]; // for enum fields → dropdown choices
  key?: string;
}

export interface Pillar {
  k: string;
  ok: boolean;
}

export interface RecordSection {
  type: string;
  fields: Field[];
}

export interface Case {
  id: string;
  source: string;
  product: string;
  queue: Queue;
  severity: Severity;
  status: Status;
  hasAdverseEvent: boolean;
  flagTitle: string;
  flagDetail: string;
  banner: string;
  receivedDate: string;
  ageDays: number;
  dueLabel: string | null;
  dueDate: string | null;
  dueUrgency: "critical" | "warning" | "normal";
  predictedClass: string | null;
  classOptions: string[];
  classConfidence: number | null;
  classRationale: string;
  classEvidence: string; // verbatim source quote behind the class (LLM-grounded)
  classReason: string;
  classNeedsReview: boolean;
  productField: Field;
  common: Field[];
  record: RecordSection | null;
  narrativeLabel: string;
  narrative: string;
  pillars: Pillar[] | null;
  isValidIcsr: boolean | null;
  sourceText: string;
}

export const CASES: Case[] = data.cases as Case[];
export const READY_COUNT: number = data.readyCount;
export const TOTAL_CASES: number = data.totalCases;
// class value → blank record template (for when the reviewer changes the class)
export const RECORD_TEMPLATES = data.recordTemplates as Record<string, RecordSection | null>;
